import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { emit } from "./emit.js";
import { fetchHeaders, resolveCommitSha } from "./fetch.js";
import { parseHeader } from "./parse.js";

export interface GenerateOptions {
  repository: string;
  ref: string;
  headers: string[];
  cacheDir: string;
  outDir: string;
}

export interface GenerateResult {
  warnings: string[];
  commitSha: string;
  ref: string;
}

export async function generate(opts: GenerateOptions): Promise<GenerateResult> {
  // Resolve the commit SHA up-front so the run fails fast if rate-limited
  // or otherwise unable to pin the ref to a real commit. Cached per-ref under
  // cacheDir so repeated runs don't hit the GitHub API unnecessarily.
  const commitSha = await resolveCommitSha({
    repository: opts.repository,
    ref: opts.ref,
    cacheDir: opts.cacheDir,
  });

  const fetched = await fetchHeaders({
    repository: opts.repository,
    ref: opts.ref,
    headers: opts.headers,
    cacheDir: opts.cacheDir,
  });

  const perFile = fetched.map((f) => ({
    path: f.path,
    result: parseHeader(f.source),
  }));

  const out = emit({ perFile });

  await mkdir(opts.outDir, { recursive: true });
  await writeFile(join(opts.outDir, "plugin-api.ts"), out.pluginApi, "utf8");
  await writeFile(join(opts.outDir, "enums.ts"), out.enums, "utf8");
  await writeFile(
    join(opts.outDir, "_meta.ts"),
    renderMeta(opts.repository, opts.ref, commitSha),
    "utf8",
  );

  return { warnings: out.warnings, commitSha, ref: opts.ref };
}

function renderMeta(repository: string, ref: string, sha: string): string {
  // Intentionally omit a generation timestamp — the output must be a pure
  // function of (repository, ref, headers) so CI drift checks are stable.
  return `// Generated by @musescore-sdk/types-generator. Do not edit by hand.
export const generatedFrom = {
  repository: ${JSON.stringify(repository)},
  tag: ${JSON.stringify(ref)},
  commitSha: ${JSON.stringify(sha)},
} as const;
`;
}

void dirname; // keep import side-effect free for ESM resolution
