import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { emit } from "./emit.js";
import { fetchHeaders, resolveCommitSha } from "./fetch.js";
import { parseHeader } from "./parse.js";

export interface GenerateOptions {
  repository: string;
  ref: string;
  headers: string[];
  cacheDir: string;
  outDir: string;
}

export interface GenerateResult {
  warnings: string[];
  commitSha: string;
  ref: string;
}

export async function generate(opts: GenerateOptions): Promise<GenerateResult> {
  const fetched = await fetchHeaders({
    repository: opts.repository,
    ref: opts.ref,
    headers: opts.headers,
    cacheDir: opts.cacheDir,
  });

  const perFile = fetched.map((f) => ({
    path: f.path,
    result: parseHeader(f.source),
  }));

  const out = emit({ perFile });

  const commitSha = await resolveCommitSha(opts.repository, opts.ref);

  await mkdir(opts.outDir, { recursive: true });
  await writeFile(join(opts.outDir, "plugin-api.ts"), out.pluginApi, "utf8");
  await writeFile(join(opts.outDir, "enums.ts"), out.enums, "utf8");
  await writeFile(
    join(opts.outDir, "_meta.ts"),
    renderMeta(opts.repository, opts.ref, commitSha),
    "utf8",
  );

  return { warnings: out.warnings, commitSha, ref: opts.ref };
}

function renderMeta(repository: string, ref: string, sha: string): string {
  return `// Generated by @musescore-sdk/types-generator. Do not edit by hand.
export const generatedFrom = {
  repository: ${JSON.stringify(repository)},
  tag: ${JSON.stringify(ref)},
  commitSha: ${JSON.stringify(sha)},
  generatedAt: ${JSON.stringify(new Date().toISOString())},
} as const;
`;
}

void dirname; // keep import side-effect free for ESM resolution
